UdpSockets.m
Replaced base64String: with string:. RCTModuleMethod's initWithObjCMethodName will not properly parse methods with numerals in their names.
=> remove numbers from method names

UdpSocket.ios.js
0.7.1 mandates that all native module require statements use the public interfafe, else the packager will fail.
https://github.com/facebook/react-native/releases/tag/v0.7.0-rc
=> Use the public interface for require statements

android/src/main/java/com/tradle/react/UdpSenderTask.java, android/src/main/java/com/tradle/react/UdpSocketClient.java, android/src/main/java/com/tradle/react/UdpSockets.java, android/src/main/java/com/tradle/react/UdpSocketsModule.java
On earlier versions of Java (I believe that's the reason), this will raise some compiler problems.
After patch:
Great library btw :+1:
=> Compile errors for empty generics definitions

UdpSocket.js
Via #12, to get hostnames working we just need to tweak the IP validator to also check for valid hostnames by the [RFC952](http://tools.ietf.org/html/rfc952) spec.
Both the [ios](https://github.com/tradle/react-native-udp/blob/master/ios/UdpSocketClient.m#L141) and [android](https://github.com/tradle/react-native-udp/blob/master/android/src/main/java/com/tradle/react/UdpSocketClient.java#L160) sockets allow a host to be a string IP or hostname.
This has been verified to work on both iOS and Android.
Closes #12.
=> Allow hostnames in addition to IP addresses

android/src/main/java/com/tradle/react/UdpSocketClient.java, android/src/main/java/com/tradle/react/UdpSockets.java
This fixes an issue on android where we had to close and create a new socket when joinGroup was called.
=> android switch to MulticastSocket for sockets

ios/UdpSocketClient.m
I'm evaluating this library for an application that sends ~60kb size UDP messages. Without this setting the messages are cut off at the default message size.
This is probably something you'd want to set with `const socket = dgram.createSocket('udp4', { maxBufferSize: 'UINT16_MAX' })`. I've modified the library to automatically choose the largest allowed size `GCDAsyncUdpSocket` allows (which is 64kb).
=> Set max buffer size to maximum allowed

UdpSocket.js, ios/CocoaAsyncSocket/GCDAsyncUdpSocket.h, ios/CocoaAsyncSocket/GCDAsyncUdpSocket.m, ios/UdpSocketClient.h, ios/UdpSocketClient.m, ios/UdpSockets.m
1. Updated GCDAsyncUdpSocket
2. Set option to reuse port if socket bound to same port twice from same IP Address
=> Fix for issue #53 - Receiving "Address Already in Use" error when binding two sockets to same port on iOS

.npmignore, package.json
The npm package being published are quite big in size (around 70MB). The npm install takes quite a lot of time while installing the package because of this. The problem is the examples folder was also being included in the npm package, which are not required for the library to run. I have added a "files" section in package.json which includes only the files/folders required for the library.
=> Don't include examples in the npm package

UdpSocket.js
The current regex for hostnames does not allow names like 0.pool.ntp.org.  0-9 is now allowed as the first character of hostnames.   An updated regex from https://www.regextester.com/23 adds 0-9 in appropriate places.
=> Issue-63: Update hostname regex to allow modern hostnames

UdpSocket.js, normalizeBindOptions.js, package.json, test/normalizeBindOptions.test.js
`bind` method should also be able to receive just one argument that is a callback function, as can be seen in [dgram source](https://github.com/nodejs/node/blob/master/lib/dgram.js#L198)
Some libraries rely on this behavior, such as [node-milight-promise](https://github.com/mwittig/node-milight-promise)
=> Allow callback to be passed as the only prop to bind

android/build.gradle
This fixes a breaking API change with the Android Gradle plugin, which was deprecated as of version 3.0.0 and later made obsolete. 
When adding Gradle dependencies, the `compile` command has been removed and replaced with `implementation`/`api`.
- [Gradle support docs](https://docs.gradle.org/5.4.1/userguide/java_library_plugin.html#sec:java_library_separation)
- [Android deprecation doc](https://developer.android.com/studio/build/dependencies?utm_source=android-studio#dependency_configurations)
=> Fix breaking change w/ Gradle dependencies

android/src/main/java/com/tradle/react/UdpReceiverTask.java
Use `InetAddress.getHostAddress()` instead of `InetAddress.getHostName()` to get the host IP. The second one sometimes returns a textual name of the local host and this info is not really useful as a source address unless there's a way to resolve that name.
=> Assure `host` is always an IP address

UdpSocket.js
RFC 952 allows only alpha numeric characters and dashes on host names.
But Huawei android devices use underscore.
This results in an error while communicating with those devices.
=> Huawei devices use underscore on host names

android/src/main/java/com/tradle/react/UdpReceiverTask.java, android/src/main/java/com/tradle/react/UdpSockets.java
This fixes #47
The `InetAddress.getHostName() `blocks and does not resolve if there is no DNS server (example using an IOT device in AP mode, e.g. ESP8266), so I'm changing it to `InetAddress.getHostAddress()` as it is non-blocking.
=> Removing blocking function

android/src/main/java/com/tradle/react/UdpSockets.java
Before, if you called `createSocket('udp4')` and `bind()` close together on production while running on a fast JS engine like Hermes, you would get the following error: `"no client found with id X"`.
This was caused because `createSocket('udp4')` was running asynchronously and had not push the new socket to the `SparseArray` when the `bind()` method was called.
=>  fix(Android): createSocket is now a blocking method

.gitignore, .npmignore, android/build.gradle, yarn.lock
I upgraded `build.gradle` in order to be able to work on it standalone via Android Studio.
`yarn.lock` had some old and unused dependencies that are not needed anymore.
=> chore: build.gradle upgrade & yarn.lock cleanup

package.json
Attribute "homepage" in package.json is required during pod install.
=> fix: Add missing attribute "homepage" to package.json

react-native-udp.podspec
Summary
Xcode 12 won't build if a module depends on React instead of React-Core. 
Reference: facebook/react-native#29633 (comment)
=> fix: Fix Xcode 12 compatibility

android/src/main/java/com/tradle/react/UdpSockets.java, ios/UdpSockets.m, src/UdpSocket.js
For doing time sync with UDP packets, the best available rx timestamp is needed to avoid delays introduced in callback event reporting.  This pull request captures the time at a low level and passes it in the rinfo callback object as a millisecond timestamp.  Verified on Android and iOS.
=> feat: Add rx timestamp to rinfo payload

android/src/main/java/com/tradle/react/UdpSenderTask.java, android/src/main/java/com/tradle/react/UdpSocketClient.java, android/src/main/java/com/tradle/react/UdpSockets.java
We were seeing an issue in Sentry due to the use of AsyncTask in the send packet  function:
It's  not occurring a lot, but enough to fix :-). The bug is hard to reproduce, we assume it's due to the Activity being paused, or the app relaunched. The AsyncTask is getting executed but the socket is no more.
Given that [https://developer.android.com/reference/android/os/AsyncTask](AsyncTask) is deprecated, I rewrote it.
_We are currently testing these change in production._
=> fix: Remove AsyncTask in the send function (it's deprecated)

android/src/main/java/com/tradle/react/UdpSockets.java
Due to my improvement: https://github.com/tradle/react-native-udp/pull/197, if you now try to send a packet to a closed channel, you get a `RejectedExecutionException` exception.
As you can see in the changed file, the send method only catches specific exceptions, and not this `RejectedExecutionException`. This actually causes an app to crash as this is unhandled.
But since this is a React Native library; it's better to catch all exceptions and pass them along to React Native. There, in your js/ts code, apps can try catch this and recover from this case.
How to reproduce?
1. open a socket
2. close a socket
3. try to send something over that closed socket
=> fix(Android): Catch all exceptions and redirect them to JS
